version: '3.0'

services:
  postgres-nestjs-db:
    image: postgres:16.1
    container_name: persistencia-objetos-orm
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME_DEVELOPMENT}
    volumes:
      - ./postgres:/var/lib/postgres/data
    ports:
      - ${DB_PORT}:${DB_PORT}
