version: '3.0'

services:
  postgres-nestjs-db-test:
    image: postgres:16.1
    container_name: backend-base-nestjs-test
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_PASS}
      POSTGRES_PASSWORD: ${DB_NAME_TEST}
    volumes:
      - ./postgres-test:/var/lib/postgres/data
    ports:
      - ${DB_PORT}:${DB_PORT}
